version: 2

builds:
  - binary: depwatch
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt

changelog:
  exclude:
    - "^docs:"
    - "^test:"
    - "^chore:"

snapshot:
  version_template: "{{ incpatch .Version }}-next"
